# app-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  type: NodePort
  selector:
    app: inventory
  ports:
    - port: 80
      targetPort: 4000
      nodePort: 30090
