apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory-container
          image: ashwinsebsatian76/inventory-app:latest  
          ports:
            - containerPort: 4000
          env:
            - name: MONGO_URI
              value: mongodb+srv://ashwinsebastian76:ashwin2001@sit725.jctfcnw.mongodb.net/?retryWrites=true&w=majority&appName=SIT725  
